extends: default.yaml
profile: integration
dataset:
  scene_limit: 1
  accepted_configurations_per_scene: 5
  accepted_episodes_per_configuration: 3
robot:
  use_final_robot: false
generation:
  native_relation_high_level_attempts: 2
  native_relation_low_level_attempts: 3

